( ( ( F G ( ( factory ) | ( iron ) ) ) & ( F G ( ! ( gem ) ) ) ) | ( F G ( gold ) ) )
( F G ( ! ( ( workbench ) & ( tree ) ) ) )
( ( G F ( ! ( iron ) ) ) | ( G F ( ( tree ) & ( workbench ) ) ) )
( G F ( factory ) )
( ( ( ( G ( factory ) ) | ( F ( ! ( tree ) ) ) ) | ( F ( workbench ) ) ) | ( ( G ( gold ) ) | ( G ( copper ) ) ) )
( F G ( ! ( gold ) ) )
( ( ( G ( tree ) ) & ( F ( ( factory ) & ( workbench ) ) ) ) | ( F ( ! ( iron ) ) ) )
( F ( ( tree ) & ( iron ) ) )
( F ( ! ( tree ) ) )
( G ( ! ( factory ) ) )
